---
title:  "[Github Blog] 블로그 게시물 작성방법" 
excerpt: "깃헙 블로그는 무엇이고 왜 쓰는 걸까?"

categories:
  - Blog
tags:
  - [Blog, Github]

toc: true
toc_sticky: true
 
date: 2024-03-03
last_modified_at: 2024-03-03

---

# 1. Java Exception

---

Java에는 Checked Exception과 Unchecked Exception이 존재

### 1.1 Checked Exception

---

- 예외 처리 필수 : `try-catch` 문으로 예외를 처리하거나 상위 메서드로 넘겨줘야 한다.
- Transaction 기본 롤백 대상이 아니라서 롤백 처리하려면 추가 처리 필요하다.
- 컴파일 단계에서 체크

### 1.2 Unchecked Exception

---

- 예외 처리 필수 아님
- Transaction 롤백 대상
- 런타임 단계에서 체크

<aside>
💡 컴파일 타임 : 기계어 코드로 변환되어 실행 가능한 프로그램이 되는 편집 과정
                       ex) Syntax 오류, Type Check 오류
런타임 :  컴파일 과정을 마친 프로그램이 동작 되는 과정
               ex) Null 참조 오류, 메모리 부족 오류

</aside>

# 2. Spring Exception의 HTTP Status

---

## 2.1. @ResponseStatus

---

```java
@ResponseStatus(code = HttpStatus.NOT_FOUND, reason = "Data Not Found")
public class DataNotFoundException extends RuntimeException{ }
```

@ResponseStatus : Http Status와 Response를 제공하는 어노테이션

개발자가 정의한 Exception이 발생하면 해당 Status와 Message를 전달한다.

### **@ResponseStatus 정의된 Custom Exception 사용**

```jsx
{
  "timestamp": "2021-03-13T07:30:38.299+00:00",
  "status": 404,
  "error": "Not Found",
  "message": "Data Not Found",
  "path": "/auth/signup"
}
```

### **한계점**

@ResponseStatus 에 정의된 대로 잘 나오지만, 위에서 정의한 DataNotFoundException은 항상 동일한 HTTP Status와 Message를  리턴한다.

즉, 같은 Exception이 발생하는 상황이라도 다른 Message를 보내는게 불가능하다.

## 2.2. ResponseStatusException

---

@ResponseStatus의 대체제로 Spring 5부터 등장

마찬가지로 HTTP Status와 Message를 설정할 수 있다.

```java
public ResponseStatusException(
		HttpStatus status,
		@Nullable String reason,
		@Nullable Throwable cause
){}
```

`Status`: HTTP Status

`reason`: HTTP response Message

`cause`: ResponseStatusException을 발생시킨 Exception

스프링에서는 **HandlerExceptionResolver** 가 모든 exception 을 가로채서 처리한다.

이 중에서 **ResponseStatusExceptionResolver** 라는 클래스가 

**ResponseStatusException** 또는 **@ResponseStatus** 어노테이션이 붙은 Exception 을 찾아서 처리해준다.

# 3. Spring 전역으로 공통 Exception 처리하기

---

### ResponseStatusException의 일반적인 사용

```java
throw new ResponseStatusException(HttpStatus.NOT_FOUND, "No Data");
```

- 다음과 같이 규격 없이, String으로만 message를 받으면, 여러 사람들이 작업할 때 중복된 응답을 주거나 이미 있는 응답을 새로 만들거나, 오타로 인해 실수 할 수 있다.

따라서 Spring Exception 처리는 다른 방법으로 진행된다.

- ErrorCode : 핵심. 모든 예외 케이스를 이곳에서 관리
- CustomException : 기본적으로 제공되는 Exception 외에 사용
- ErrorResponse : 사용자에게 JSON 형식으로 보여주기 위해 에러 응답 형식 지정
- GlobalExceptionHandler : Custom Excepton Handler
    - @ControllerAdvice : 프로젝트 전역에서 발생하는 Exception을 잡기 위한 클래스
    - @ExceptionHandler : 특정 Exception을 지정해서 별도로 처리해줌

## 3.1. ErrorCode

---

```java
@Getter
@AllArgsConstructor
public enum ErrorCode {

    /* 400 BAD_REQUEST : 잘못된 요청 */
    INVALID_REFRESH_TOKEN(400, BAD_REQUEST, "리프레시 토큰이 유효하지 않습니다"),
    MISMATCH_REFRESH_TOKEN(400, BAD_REQUEST, "리프레시 토큰의 유저 정보가 일치하지 않습니다"),
    CANNOT_FOLLOW_MYSELF(400, BAD_REQUEST, "자기 자신은 팔로우 할 수 없습니다"),

    /* 401 UNAUTHORIZED : 인증되지 않은 사용자 */
    INVALID_AUTH_TOKEN(401, UNAUTHORIZED, "권한 정보가 없는 토큰입니다"),
    UNAUTHORIZED_MEMBER(401, UNAUTHORIZED, "현재 내 계정 정보가 존재하지 않습니다"),

    /* 404 NOT_FOUND : Resource 를 찾을 수 없음 */
    MEMBER_NOT_FOUND(404, NOT_FOUND, "해당 유저 정보를 찾을 수 없습니다"),
    REFRESH_TOKEN_NOT_FOUND(404, NOT_FOUND, "로그아웃 된 사용자입니다"),
    NOT_FOLLOW(404, NOT_FOUND, "팔로우 중이지 않습니다"),

    /* 409 CONFLICT : Resource 의 현재 상태와 충돌. 보통 중복된 데이터 존재 */
    DUPLICATE_RESOURCE(409, CONFLICT, "데이터가 이미 존재합니다"),

    ;

		private final int status;
    private final String errorCode;
    private final String message;
}
```

- 에러 형식을 Enum 클래스로 정의한다.
- 응답으로 내보낼 HttpStatus와 에러 메시지로 사용할 String을 갖고 있다.
- 개발자가 정의한 새로운 Exception을 모두 한 곳에서 관리하고 재사용 할 수 있다.

## 3.2. CustomException

---

```java
@Getter
@AllArgsConstructor
public class CustomException extends RuntimeException {
    private final ErrorCode errorCode;
}
```

- 전역으로 사용할 CustomException
- `RuntimeException` 을 상속받아서 Unchecked Exception 으로 활용한다.
- 생성자로 `ErrorCode` 를 받는다.

## 3.3. ErrorResponse

---

```java
@Getter
@Builder
public class ErrorResponse {
    private final LocalDateTime timestamp = LocalDateTime.now();
    private final int status;
    private final String error;
    private final String code;
    private final String message;

    public static ResponseEntity<ErrorResponse> toResponseEntity(ErrorCode errorCode) {
        return ResponseEntity
                .status(errorCode.getHttpStatus())
                .body(ErrorResponse.builder()
                        .status(errorCode.getHttpStatus().value())
                        .error(errorCode.getHttpStatus().name())
                        .code(errorCode.name())
                        .message(errorCode.getDetail())
                        .build()
                );
    }
}
```

- 실제로 유저에게 보낼 응답 Format
- ErrorCode를 받아서 ResponseEntity<ErrorResponse>로 변환해준다.

## 3.4. @ControllerAdvice 와 @ExceptionHandler

---

@RestControllerAdvice 는 프로젝트 전역에서 발생하는 모든 예외를 잡아준다.

@ExceptionHandler 는 발생한 특정 예외를 잡아서 하나의 메소드에서 공통 처리해줄 수 있게 해준다.

```java
@Slf4j
@RestControllerAdvice
public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {

    @ExceptionHandler(value = { ConstraintViolationException.class, DataIntegrityViolationException.class})
    protected ResponseEntity<ErrorResponse> handleDataException() {
        log.error("handleDataException throw Exception : {}", DUPLICATE_RESOURCE);
        return ErrorResponse.toResponseEntity(DUPLICATE_RESOURCE);
    }

    @ExceptionHandler(value = { CustomException.class })
    protected ResponseEntity<ErrorResponse> handleCustomException(CustomException e) {
        log.error("handleCustomException throw CustomException : {}", e.getErrorCode());
        return ErrorResponse.toResponseEntity(e.getErrorCode());
    }
}
```

## 3.5 Exception 사용

```java
@RequiredArgsConstructor
@Service
public class MemberService {
    private final MemberRepository memberRepository;

    @Transactional
    public boolean follow(Long memberId) {
        Member currentMember = getCurrentMember();

        // 팔로우할 상대방 정보가 없는 경우
        Member targetMember = memberRepository.findById(memberId)
                .orElseThrow(() -> new CustomException(MEMBER_NOT_FOUND));

        // 자기 자신을 팔로우 하려는 경우
        if (currentMember.equals(targetMember))  {
            throw new CustomException(CANNOT_FOLLOW_MYSELF);
        }

                // code...
    }
}
```

### MEMBER_NOT_FOUND 실제 응답

```java
{
  "timestamp": "2021-03-14T03:29:01.878659",
  "status": 404,
  "error": "NOT_FOUND",
  "code": "MEMBER_NOT_FOUND",
  "message": "해당 유저 정보를 찾을 수 없습니다"
}
```

### CANNOT_FOLLOW_MYSELF 실제 응답

```java
{
  "timestamp": "2021-03-14T03:16:25.98361",
  "status": 400,
  "error": "BAD_REQUEST",
  "code": "CANNOT_FOLLOW_MYSELF",
  "message": "자기 자신은 팔로우 할 수 없습니다"
}
```